
<style>
.wizpay-popup-body-content iframe{
    width: 100%;
    min-height: 920px;
}

</style>



<div id="wizpay-modal-content">
    <div class="modal-body-content wizpay-popup-body-content">
        <iframe src="https://info.wizpay.com.au/HowItWorks/HowItWorks.html" title="Terms and Conditions">
        </iframe>
    </div>    
</div>



<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            title: 'Terms and Conditions',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#wizpay-modal-content'));
        $(".wizpay-learn-more-popup-link").click(function() {
            $('#wizpay-modal-content').modal('openModal');
        });
    });
</script>